# @package _global_
model_module:
  _target_: src.models.tfm_mlp.Noise_MLP_Cond_Memory_Module
  time_varying: true
  conditional: true
  treatment_cond: 0
  memory: 4
  dim: 2
  w: 256
  lr: 1e-3
  clip: 0.1
  sigma: 0.05
  metrics:
    - mse_loss
    - l1_loss
    