defaults:
  - data_module: eth
  - model: tfm_mlp
  - trainer: default
  - clearml: default
  - _self_

seed: 0xDEADBEEF
skip_training: false

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: true
